apiVersion: v1
kind: Service
metadata:
  name: cafestaticexam
  labels:
    app: cafestaticexam
spec:
  type: NodePort
  selector:
    app: cafestaticexam
  ports:
    - port: 89        # Service port
      targetPort: 80  # Container port
      protocol: TCP
